# Generated by Django 5.0.3 on 2024-04-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0002_objectsdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectsData',
        ),
    ]
