# Generated by Django 5.0.3 on 2024-04-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0004_objectsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsdata',
            name='status',
            field=models.CharField(choices=[('p', 'Published'), ('d', 'Draft')], default='d', max_length=1),
        ),
    ]
