# Generated by Django 5.0.3 on 2024-06-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0007_objectsdata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsdata',
            name='url',
            field=models.SlugField(default='object', max_length=130),
        ),
    ]
