# Generated by Django 5.0.3 on 2024-06-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0009_remove_objectsdata_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsdata',
            name='url',
            field=models.SlugField(default='objects', max_length=130),
        ),
    ]
